### ISSUE TITLE
Test plugin on Windows / macOS

### ISSUE THREAD

**Issue by exigow** [exigow/intellij-gdscript#17]

**Comment by adrian-goe** [comment]
Hey, I can test this in intelliJ Ultimate on macOS.

**Comment by exigow** [comment]
Thanks @adrian-goe!

Testing code completion like `"res://"` or run configurations would be helpful. I guess there can be issue with difference between slash and backshash and in the way that these path strings are represented, but this might concern only Windows. On macOS this probably works because of the similarity to Linux, but I'm not sure about default run configurations for scene/projects.

Also, feedback would be nice, in fact. :smile:

**Comment by exigow** [comment]
FYI releases might be slightly outdated so it's better to clone + `./gradlew runIde`

**Comment by Bromeon** [comment]
Hello, and great to see that this plugin is actively being developed! 😎 

I cloned latest master and ran `gradlew runIde` on Windows 10. After it downloaded and installed IntelliJ IDEA Community 2019.2 (built July 2019), I tinkered around a bit with a Godot project.

I opened the Godot root folder (the one that acts as `res://` root)  -- once directly as a project, and once with _Import from existing sources_. As far as I could tell, it didn't matter.

-----
My observations:

### Code completion

* `"res://"` strings
   * Works if the .gd file is in the project root, but **not** inside nested files -- the tooltip _No suggestions_ appears
   * I was first confused that it shows nested files directly. I think it may be convenient if you know the file name rather than the file structure, however I was really confused that directories did not show up at all. So it's impossible to start typing `"res://as` and to be completed to `"res://assets/"`.
   * The completion only starts when pressing Ctrl+Space. Maybe this has performance reasons, but I'm generally used to get implicit context information in IntelliJ. This is also the case for e.g. GDScript function name completion in this plugin.

 * Functions
   * [Built-in functions](https://docs.godotengine.org/en/3.1/classes/class_@gdscript.html) like `print`, `acos`, etc. are suggested as soon as I start typing the first letters
   * Functions defined in current class are **not** suggested (even after Ctrl+Space)
   * Member functions of any variable are **not** suggested, even if the variable type is declared (I guess this is not implemented yet)

* Types/classes
  * Type annotations in variable declaration `var a: type` is completed with all possible Godot nodes and resources
  * Completion after `extends` works as well
  * Completion for function parameter types works
  * Completion for function return types works, however `void` is missing from the list

* Constants/enums/variables
  * [Those in global scope](https://docs.godotengine.org/en/3.1/classes/class_@globalscope.html) are suggested when typing
  * Constants/enums declared in current file are **not** suggested
  * Class-scope (member) variables are **not** suggested
  * Function-local variables are **not** suggested

### Run configurations

* Right-click scene file (project structure UI or directly on the editor tab) > Run
  * Creates always a new run configuration, even if one is already defined for that file -- it should probably reuse existing ones
  * On first time, it does not open a UI to prompt for settings -- instead it attempts some defaults (e.g. Godot executable has Linux `/usr/bin/godot` path) which don't work

* From _Run/Debug Configurations_ UI
  * I did this to fix the previously created run configurations, via _Edit Configurations_ at top of IDE
  * Field _Godot executable_ seems to expect a directory path, not a file path -- after choosing the location of the Godot .exe file, it apparently tries to execute the directory and fails with: 
       > Cannot run program [...]: CreateProcess error=5, Access is denied
  * After manually fixing the executable path (to point to the .exe), it works!
  * After that, clicking the green Play button works as well
  * Stop and Rerun seem to work as well

Probably a lot of those are not new to you 🙂

Thanks a lot for working on this plugin, adding the IntelliJ platform to Godot's ecosystem will be very valuable! 👍

**Comment by exigow** [comment]
Hi @Bromeon,

> Works if the .gd file is in the project root, but not inside nested files -- the tooltip No suggestions appears

Completion in nested directories should work. That's definitely an issue on Windows. I'll work on that.

> I was first confused that it shows nested files directly. I think it may be convenient if you know the file name rather than the file structure, however I was really confused that directories did not show up at all. So it's impossible to start typing "res://as and to be completed to "res://assets/".

True, that's might be confusing. Prioritizing completions by number of subdirectories should fix that. Added https://github.com/exigow/intellij-gdscript/issues/23.

> The completion only starts when pressing Ctrl+Space. Maybe this has performance reasons, but I'm generally used to get implicit context information in IntelliJ. This is also the case for e.g. GDScript function name completion in this plugin.

That must be a bug because all completion works for me without mentioned shortcut. Typing first character is always enough. Do you have some non-default options related to completion? I will try to reproduce this on VM.

> When starting with a prefix, the completion correctly shows only the files in that directory (e.g. after typing "res://assets/ and pressing Ctrl+Space)

Works as expected.

> Windows-style path separators as in "res://assets\ do not work -- which is fine, since Godot does not support those.

Thanks for the link. I didn't know that. I've created such inspection in `aadb1fe1521826839e837cc2aff7ecf0385acb50`.

> Built-in functions like print, acos, etc. are suggested as soon as I start typing the first letters

I may have gotten used to these instant suggestions. :smile: Do you think they should appear later, for example on second/third letter?

> Type annotations in variable declaration var a: type is completed with all possible Godot nodes and resources
> Completion after extends works as well
> Completion for function parameter types works

Works as expected.

> Completion for function return types works, however void is missing from the list

Fixed in `b919950d71d734dec82040967de6211e2fa146b1`.

> Member functions of any variable are not suggested, even if the variable type is declared (I guess this is not implemented yet)
> Those in global scope are suggested when typing
> Functions defined in current class are not suggested (even after Ctrl+Space)
> Constants/enums declared in current file are not suggested
> Class-scope (member) variables are not suggested
> Function-local variables are not suggested

That's correct. It's not implemented yet (https://github.com/exigow/intellij-gdscript/issues/24).

> Creates always a new run configuration, even if one is already defined for that file -- it should probably reuse existing ones

Thank's for noticing this detail. Added https://github.com/exigow/intellij-gdscript/issues/25.

> On first time, it does not open a UI to prompt for settings -- instead it attempts some defaults (e.g. Godot executable has Linux /usr/bin/godot path) which don't work
> I did this to fix the previously created run configurations, via Edit Configurations at top of IDE

Value is hardcoded. :laughing: Added https://github.com/exigow/intellij-gdscript/issues/26.

I've also noticed that config load/save features are not working properly. That was fixed too with latest changes.

> Field Godot executable seems to expect a directory path, not a file path -- after choosing the location of the Godot .exe file, it apparently tries to execute the directory and fails with: Cannot run program [...]: CreateProcess error=5, Access is denied

This has been fixed in current master.

I will fix the rest of these issues soon. Huge thanks for your comments! :thumbsup:

**Comment by rankala** [comment]
hi, first of all: sorry it took so long. a few private things came up.

I started the IDE and directly got 3 errors. [Gist with Stacktrace](https://gist.github.com/rankala/03dd2bf34f2695137d43ffbfd4aa619e#file-stacktarce-md)

Unfortunately I can't get it with the errors that any files are displayed. Intellij only shows loading.

I hope this helps. If not, please contact me again. Write me also gladly a PM, then I can give you direct contact data.

**Comment by exigow** [comment]
Hi @rankala,
thank you for sending stacktrace. Exception has been caused by incompatible parser/lexer bytecode with installed JVM. It has been fixed in `8477a3f2912cdc229e584ef0c62f53f3f8db7d37`. Please let me know if there are still some issues.

**Comment by rankala** [comment]
Hi @exigow,
yes. So far it looks very good. Code is loading correctly.
The thing with "res://" works and works also in a subdir.

One thing I noticed, autocompletion with . doese not work.
My expectation would be, if I call an object like a vector and write . that I get the inner variables suggested like x/y. Also functions.

I will take a closer look at this later today.

**Comment by exigow** [comment]
I think this old issue can be closed. New bugs should be posted as a separate issues.

Thank you all for your help.
