### ISSUE TITLE
Is not shown in IDEA/Rider marketplace search

### ISSUE THREAD

**Issue by van800** [exigow/intellij-gdscript#45]
![image](https://user-images.githubusercontent.com/1482681/75961041-8158c900-5ec1-11ea-8066-598642372b3f.png)

At least for IDEA 2019.3.3 and Rider 2020.1

**Comment by exigow** [comment]
Hi @van800,

plugin is hidden because all releases are on [beta channel](https://plugins.jetbrains.com/plugin/13107-gdscript/versions).

I'm going to publish stable release after achieving [first milestone](https://github.com/exigow/intellij-gdscript/milestone/1). There is only one issue left so it's a matter of a few days max.

This is motivated by the fact that I would like to test the plugin first to provide at least _decent_ developer experience before making it available to a wider group of users.

**Comment by exigow** [comment]
BTW if you have any thoughts, insights or encountered some issues - please let me know. Every information is very valuable, especially since few people had the opportunity to test this plugin.

**Comment by exigow** [comment]
@van800, plugin is now searchable.

https://plugins.jetbrains.com/plugin/13107-gdscript/versions
