### ISSUE TITLE
Functions not highlighted

### ISSUE THREAD

**Issue by Izmoqwy** [exigow/intellij-gdscript#46]
Functions are not highlighted. Only built-in such as str(), preload() & randomzie() are highlighted but others are not.
![Screenshot_2020-03-07_21-05-07](https://user-images.githubusercontent.com/30635699/76151662-9c8d2980-60b7-11ea-9b35-e4214d4909bd.png)

**Comment by Izmoqwy** [comment]
I've got some other questions about this project, they're probably unrelated but idk where to ask them.
Can you add auto-completion for gdscript methods? (like _ready(), _process(), etc)
Do you plan to add error highlighting?
Do you plan to setup references & resolve? (for rename refactoring & find usages)
Do you plan to add full code completion? (variables, custom classes, methods from classes)

If any of these is answered by yes or maybe, how much time do you think it will take?

**Comment by exigow** [comment]
Hi @Izmoqwy,

let me answer your questions:

> Functions are not highlighted. Only built-in such as str(), preload() & randomzie() are highlighted but others are not.

Currently only two types of functions are highlighted: language-level functions (for example `preload()`, like you mentioned) and static functions (like `Input.is_key_pressed()`). More are planned.

>  Can you add auto-completion for gdscript methods? (like _ready(), _process(), etc)

Good idea. Should be easy to add because class extensions can easily be predicted (eg `extends` on top). But I'm not sure about nested classes - I'm afraid of false positives.

>  Do you plan to add error highlighting?

Yes, and this is a priority because this can drastically increase developer experience. Besides, I'm currently working on clickable console links and it's almost done: https://github.com/exigow/intellij-gdscript/issues/44

>  Do you plan to setup references & resolve? (for rename refactoring & find usages)

Yes, this is very important to add and it's on my TODO's.

>  Do you plan to add full code completion? (variables, custom classes, methods from classes)

Yes, but it is the hardest part. Parsing Python-like languages is very tricky (it's indentation-based with a lot of syntactic sugars).

Let me know if you have any more questions. And sorry for the late reply - I've been busy the last few days.

**Comment by exigow** [comment]
@Izmoqwy, FYI console errors are now "clickable".

https://i.imgur.com/2Oqmnd0

**Comment by Izmoqwy** [comment]
Hi, thank you for your answers. I'm glad you plan to do everything because implementing these features makes development a lot faster and more enjoyable.
Good luck for the tricky parts!
