### ISSUE TITLE
Autocomplete behaving wierdly

### ISSUE THREAD

**Issue by xphlawlessx** [exigow/intellij-gdscript#74]
using Pycharm pro , godot 3.2.3

when typing "var" it autocompletes to "vartobytes()" and when typing "func" it autocompletes to "funcref()"
I've never made anything like this  but to me it looks like it only autocomplete's class and method names, no language keywords. this is pretty frustrating for someone who uses thier IDE as a crutch like i do , haha :D

**Comment by loohoo** [comment]
this is very bad plugin. you can use vscode + godot plugin, it's very nice!

**Comment by exigow** [comment]
Hi @xphlawlessx,
your issue has been fixed in version 0.34.1, commit 774514110a9aa0d8c32bf8dfabb1830497297c81. Please note that this version is currently available on **beta** channel so it has to be downloaded manually. Let me know if that's what you expected / any feedback will be appreciated.

Link to version 0.34.1: https://plugins.jetbrains.com/plugin/13107-gdscript/versions/beta/144625

**Comment by xphlawlessx** [comment]
Amazing , thank you so much. What a hero !

**Comment by exigow** [comment]
Thanks @xphlawlessx,
in the meantime, I made some new improvements in [0.34.5](https://plugins.jetbrains.com/plugin/13107-gdscript/versions/beta/144782). More details are available in related PR discussion: https://github.com/exigow/intellij-gdscript/pull/82

If everything works as expected please mark this issue as resolved. Even a simple "OK" feedback will be very valuable because the plugin on the beta channel is almost invisible to users. :slightly_smiling_face:
